### ISSUE TITLE
User-Agent should not be spoofed

### ISSUE THREAD

**Issue by aqw** [psyinfra/ups-prometheus-exporter#10]
In `scraper_globals.py`, the headers for both `LOGIN_` and `AUTH_` are hardcoded. It is considered poor form to spoof the headers unnecessarily.

Unless they are sniffing for user agents (which would be worthy of a snarky comment in the source code), nothing in those headers looks atypical. Ideally, they can all be removed and the defaults used.

**Comment by mathisloevenich** [comment]
These are not the final headers, they are getting manipulated in the actual section with the data that is not static. I thought it would be nice to outsource the most of hardcoded stuff to make the actual code less complex.

**Comment by mathisloevenich** [comment]
Ah well I see that these are actually redundant. 
But as the auth header gets an authentication token added,
I am curious if it makes a difference when I pass the header with simply 
`Authorization: bla bla`. 
Does this then still have all the other defaults like `Connection:keep-alive`?

If it does no problem.

**Comment by aqw** [comment]
I'm unsure. You'll need to read `requests`s docs to see what they're doing by default. But agree the majority, if not all, of those headers are unnecessary.

**Comment by mathisloevenich** [comment]
It seems that is works without all the headers. 
Good to know that default headers exist

**Comment by mathisloevenich** [comment]
I did not find any issues with that so I guess we can close this issue again.
