### ISSUE TITLE
percent should be "ratio"

### ISSUE THREAD

**Issue by aqw** [psyinfra/ups-prometheus-exporter#11]
Prometheus best practice is to use "ratio": rather than percent. https://prometheus.io/docs/practices/naming/#base-units

The field names should be updated to end in `_ratio` rather than `_percent`. And the values should be changed accordingly.

**Comment by mathisloevenich** [comment]
So would this mean `ups_output_percent_load_in_percent` should rather be `ups_output_percent_load_ratio` ?

**Comment by aqw** [comment]
Correct. And the value itself should be (for example) `0.82` instead of `82`.

**Comment by mathisloevenich** [comment]
Ah okay, I've just exposed the data as it is given by the API.
Is it a common thing to change the format of the scraped data?

**Comment by mathisloevenich** [comment]
Done

**Comment by aqw** [comment]
For something as simple as this, it definitely makes sense. If we normalize the data flowing into Prometheus, it makes it much easier to reuse graphs and compare across systems.

However, in other situations, we ignore it. For example, Prometheus suggests using joules rather than watts. IMO, it's not worth it to adjust our watt metrics into joules, so we'll leave them as they are. :-)

**Comment by nhjjr** [comment]
Sorry to bug again on this issue, but it's better to prefix metrics with `eaton_ups_*` instead of `ups_*`, because this exporter only works for eaton UPS's.

**Comment by mathisloevenich** [comment]
Alright I will make the changes

**Comment by nhjjr** [comment]
Alex has addressed this in PR #15 already. If you can validate it and merge it to master, then we can run it and I'll set up the accompanying Eaton UPS Dashboard.

**Comment by mathisloevenich** [comment]
I just saw it.

**Comment by mathisloevenich** [comment]
Merged
