### ISSUE TITLE
regression: --web.listen-address no longer allows listening on all interfaces

### ISSUE THREAD

**Issue by aqw** [psyinfra/ups-prometheus-exporter#12]
The following syntax used to result in the exporter listening on all network interfaces:

```
--web.listen-address :9790"
```

In the new release, it results in listening on `127.0.0.1`.

**Comment by mathisloevenich** [comment]
Ah I hope you were still able to deploy it. I've added some code to prevent people using strange syntax, like : `--web.listen-address 127.0.0.1:"`

**Comment by mathisloevenich** [comment]
I will change that back as I was not aware of this fact.
