### ISSUE TITLE
document values of battery health (if possible)

### ISSUE THREAD

**Issue by aqw** [psyinfra/ups-prometheus-exporter#16]
Right now it's a 5.0. I have no idea if that means healthy or actively on fire. ;-)

**Comment by mathisloevenich** [comment]
Me neither, I'm just exposing the data.

Let's see if there is some documentation for this.

**Comment by mathisloevenich** [comment]
Oops, I closed the wrong one.

**Comment by mathisloevenich** [comment]
Closing since #19 is covering that topic now
