### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Alanbrtd** [psyinfra/ups-prometheus-exporter#22]
Hello,
When I run the script, I get this error: 
![image](https://user-images.githubusercontent.com/54882604/164018428-69a80fb7-fdda-4ea4-b7a8-a409b9f4b38b.png)

Do you have any ideas to help me ? I have the Eaton Network Card-M2.

Have a nice day :)

**Comment by mathisloevenich** [comment]
Seems that your web-interface has a different setup than the one that I used before.
I can't really help you with your problem, as you have to figure out yourself what the differences are.
It seems that you don't have the attribute realtime in the inputs['measures'].
You could try to remove the lines from the code that are causing issues and move on from there.

**Comment by mathisloevenich** [comment]
It's been almost a year and no further questions have been asked to keep this issue open, so I will close it now

**Comment by WatchCollector67** [comment]
I stumbled upon this today, I have 3 of the same UPS's with all the same network card. 
 

2x of my UPS's are on Network Card Firmware 1.7.5 with one of them on 2.0.5 somehow, this error appears on my UPS with the 2.0.5 Firmware, suggesting Eaton changed something somewhat recently with the way input measures are called upon.

Unfortunately I'm not well versed enough to figure out what causes the issue, although it may be possible to upgrade your firmware to 2.0.5 and figure it out for yourself. There is also a 3.0 version firmware, seems they really did support this product decently!

For anyone reading this, do not upgrade your Firmware if you wish to keep using this amazing exporter, thanks for making it! (:

**Comment by nhjjr** [comment]
> I stumbled upon this today, I have 3 of the same UPS's with all the same network card.
> 
> 2x of my UPS's are on Network Card Firmware 1.7.5 with one of them on 2.0.5 somehow, this error appears on my UPS with the 2.0.5 Firmware, suggesting Eaton changed something somewhat recently with the way input measures are called upon.
> 
> Unfortunately I'm not well versed enough to figure out what causes the issue, although it may be possible to upgrade your firmware to 2.0.5 and figure it out for yourself. There is also a 3.0 version firmware, seems they really did support this product decently!
> 
> For anyone reading this, do not upgrade your Firmware if you wish to keep using this amazing exporter, thanks for making it! (:

I have moved this to a new issue (#23)
