### ISSUE TITLE
rename repo to prometheus-eaton-ups-exporter

### ISSUE THREAD

**Issue by aqw** [psyinfra/ups-prometheus-exporter#7]
This will follow common norms in the Prometheus community, and will also make clear that only Eaton UPSs are targeted.

**Comment by mathisloevenich** [comment]
As I merged your last change on that, I will close this issue.

**Comment by aqw** [comment]
You merged my PR which renamed the library and the script name. The repo (which is what this issue is about) needs to be renamed by you. ;-)

**Comment by mathisloevenich** [comment]
LMAO I misunderstood this

**Comment by mathisloevenich** [comment]
Done

**Comment by aqw** [comment]
:-D
